name: Development

on:
  pull_request:
    branches:
      - development
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Make dev and test config
      run: cp config/dev.example.exs config/dev.exs && cp config/test.example.exs config/test.exs

    - name: Set up Elixir
      uses: erlef/setup-beam@988e02bfe678367a02564f65ca2e37726dc0268f
      with:
        elixir-version: '1.13.0'
        otp-version: '24.1'

    - name: Restore dependencies cache
      uses: actions/cache@v2
      id: deps_cache
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}-deps

    - name: Install dependencies
      if: steps.deps_cache.outputs.cache-hit != 'true'
      run: mix deps.get

    - name: Restore Dialyzer PLT cache
      uses: actions/cache@v2
      id: plt_cache
      with:
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}-plt
        path: |
          priv/plts

      # Create PLTs if no cache was found
    - name: Create Dialyzer PLTs
      if: steps.plt_cache.outputs.cache-hit != 'true'
      run: mix dialyzer --plt

    - name: Run checks
      run: mix check 
