name: Master

on:
  pull_request:
    branches:  
      - master 
jobs:
  build:
    name: Validate branch
    runs-on: ubuntu-latest

    steps:
      - name: Triggered by development
        run: echo "$GITHUB_HEAD_REF" && if [[ "$GITHUB_HEAD_REF" == 'development' ]]; then exit 0; else exit 1; fi;
